# $HOME/.config/alacritty/alacritty.toml
import = [
    "~/.config/alacritty/themes/themes/kanagawa_dragon.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
# opacity = 0.95
# blur = true

padding.y = 10
padding.x = 10

decorations = "Buttonless"
decorations_theme_variant = "Dark"

[font]
size = 18
# normal.family = "Hack Nerd Font"
# bold.family = "Hack Nerd Font"
# italic.family = "Hack Nerd Font"
# bold_italic.family = "Hack Nerd Font"

normal.family = "JetBrainsMono Nerd Font Mono"
bold.family = "JetBrainsMono Nerd Font Mono"
italic.family = "JetBrainsMono Nerd Font Mono"
bold_italic.family = "JetBrainsMono Nerd Font Mono"

