# $HOME/.config/alacritty/alacritty.toml
import = [
    "~/.config/alacritty/themes/themes/kanagawa_dragon.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
# opacity = 0.95
# blur = true

padding.y = 10
padding.x = 10

decorations = "Buttonless"
decorations_theme_variant = "Dark"

[font]
size = 18
# normal.family = "Hack Nerd Font"
# bold.family = "Hack Nerd Font"
# italic.family = "Hack Nerd Font"
# bold_italic.family = "Hack Nerd Font"

normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"

[keyboard]
bindings = [
{ key= "Left", mods= "Alt", chars= "\u001BB" } # Skip word left
,{ key= "Right", mods= "Alt", chars= "\u001BF" } # Skip word right
,{ key= "Left", mods= "Command", chars= "\u001bOH", mode= "AppCursor" } # Home
,{ key= "Right", mods= "Command", chars= "\u001bOF", mode= "AppCursor" } # End
,{ key= "Back", mods= "Command", chars= "\u0015" } # Delete line
,{ key= "Back", mods= "Alt", chars= "\u001b\u007f" } # Delete word
]
